### PR TITLE
Deleting queues that no longer exist in OSOB

### PR DESCRIPTION
**Pull request by lukas-lansky**
Checked according to `windows.yaml`

### CODE REVIEW

**Comment by lukas-lansky** [comment]
I wonder about the other direction too. Is there a point in having `BuildPool.` definition in OSOB that is not referenced from here?

**Review by MattGal — CHANGES_REQUESTED** [review]
These changes are not valid.   I started at the top of the prod list:

**Review by MattGal — APPROVED** [review]
Looks good now.

**Comment by lukas-lansky** [comment]
Interesting, who would have though that the Linux queues are defined at a slightly distinct file. Thanks!

With regards to for example [`BuildPool.Server.Amd64.ES.VS2017.Open`](https://helix.dot.net/api/info/queues/BuildPool.Server.Amd64.ES.VS2017.Open?api-version=2019-06-17), where does these metadata coming from? I don't see a living scaleset backing that queue. I don't see definition in helix-machines. And still, the API remembers it.

**Comment by MattGal** [comment]
> Interesting, who would have thought that the Linux queues are defined at a slightly distinct file. Thanks!
> 
> With regards to for example [`BuildPool.Server.Amd64.ES.VS2017.Open`](https://helix.dot.net/api/info/queues/BuildPool.Server.Amd64.ES.VS2017.Open?api-version=2019-06-17), where does these metadata coming from? I don't see a living scaleset backing that queue. I don't see definition in helix-machines. And still, the API remembers it.

Those were corrected in the last week from being disabled, but still existing and being forwarded to deadletter.  Switch your API to helix.int-dot.net and it will show you what will be the prod state on Weds.  If you need help seeing where the JSON file backing the API's queue info representation is I can go into more detail.

**Comment by lukas-lansky** [comment]
I get it, they were deadlettered and that's why there is no scaleset even in production.

**Pull request merged**
